name: Nubis Development
tagline: Young, enthusiastic development team with a passion for anything new.
gplus_id: 111860592124351326118
base_url: http://development.nub.is

contact:
  email: development@nubisonline.nl
  phone: 003120-8932941

permalink: pretty
pygments: true

source_link: https://github.com/nubisonline/development-blog/blob/source/

ga_code: UA-43461893-1

authors:
  tim:
    display_name: Tim
    full_name: Tim van Dalen
    gplus_id: 100487696573936783003
    position: Head of Development
  walid:
    display_name: Walid
    full_name: Walid Said
    gplus_id: 104993994538898250860
    position: Senior Developer
  remco:
    display_name: Remco
    full_name: Remco Plasmeijer
    gplus_id: 102632274470030995679
    position: Systems Architect
  robbert:
    display_name: Robbert
    full_name: Robbert Jongeling
    gplus_id: 111701719727853867628
    position: Junior Developer

